### ISSUE TITLE
[android]webview播放视频就崩溃android.permission.WAKE_LOCK

### ISSUE THREAD

**Issue by mic101** [mic101/mic101.github.io#23]
, 0, 0)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ java.lang.SecurityException: Neither user 10094 nor current process has android.permission.WAKE_LOCK.
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.os.Parcel.readException(Parcel.java:1465)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.os.Parcel.readException(Parcel.java:1419)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:311)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:730)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.os.PowerManager$WakeLock.acquire(PowerManager.java:699)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.media.MediaPlayer.stayAwake(MediaPlayer.java:1675)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.media.MediaPlayer.start(MediaPlayer.java:1582)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at com.android.org.chromium.media.MediaPlayerBridge.start(MediaPlayerBridge.java:95)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.os.Looper.loop(Looper.java:153)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5032)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851)
04-29 17:23:35.090    3116-3116/com.dabaijing.browser W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:667)

**Comment by mic101** [comment]
http://www.cnblogs.com/over140/archive/2011/11/17/2252210.html
